### ISSUE TITLE
Signed-in user name misalignment

### ISSUE THREAD

**Issue by djohnstonCC** [aliss/ALISS#10]
When a registered user signs in, their name is displayed in the top right hand corner of the screen, inside `div class="top-hat"`. 

The name is currently displayed at font-weight 700 and font-size 19.2px, and is slightly mis-aligned with  the other elements.
The 'Logout' link to the right of the username is displayed at font-weight 400 and font-size 19.2px
The 'Give Feedback' button to the right of the 'Logout' link displays its text at font-weight 400 and font-size 21.6px. 

The combined effect of this is a little jarring. It may be useful to realign the elements and standardise on a single weight and/or font size. 

![capture2](https://user-images.githubusercontent.com/27961930/45034699-1d491080-b050-11e8-8c46-57411adb9fc8.PNG)

**Comment by digitalWestie** [comment]
now fixed on staging, will be pushed to production shortly
