### ISSUE TITLE
'Send Recommendations' tool lacks empty/null validation

### ISSUE THREAD

**Issue by djohnstonCC** [aliss/ALISS#12]
Steps to reproduce:
Register as an ALISS user
Sign in
Navigate to user account page
Navigate to 'My Recommendations' page (https://www.aliss.org/account/my-recommendations/)
Create a recommendations list by inputting a string
Recommendations list updates with new recommendation
Click 'Email recommendations'
Input valid email address
Click 'Send'

Expected behaviour:
Notification that recommendations are currently empty, i.e. no content to send

Actual behaviour:
Empty recommendations list is sent to recipient

**Comment by digitalWestie** [comment]
fixed
