### ISSUE TITLE
User digest

### ISSUE THREAD

**Issue by digitalWestie** [aliss/ALISS#2]
Create a form that allows user to add a postcode(s) w/ categories - e.g. digest for postcode "EH4 4EB", categories "Money", "Health"

Create a digest page where they can see all the postcode + categories they've setup

For each postcode in page display listing of the latest 3 services updated in each of their saved categories

On same page show any "Saved services" that have been updated in the last week

----

1. Create a new view and template that pulls in saved service that have been updated in the past X (default to a week) amount of time. Link to the new digest view from the user account tabs.

2. On the same page, choose a few postcodes, plus one or more categories for each, and display the 3 most up to date services.

3. Create a new model `digest_area`, which stores user it belongs to, postcode, and many to many categories relationship (test by adding data to db via shell)

4. Implement the create page & form for user to set up digests

**Comment by digitalWestie** [comment]
Do we only want new services? What about recently updated?

**Comment by Mike-Heneghan** [comment]
Digest view URL should follow the path to my-digest i.e. 
```
    url(r'^my-digest/$',
        AccountMyDigestView.as_view(),
        name='account_my_digest'
    )
```

**Comment by Mike-Heneghan** [comment]
- [ ] Create a new view to extract information from the model about the saved_services updated in the last x weeks.

- [ ] Create a template that renders a list of the dsaved services pulled in from the model.

**Comment by Mike-Heneghan** [comment]
Need to solve geocoder error to add specific locations to local db.

**Comment by Mike-Heneghan** [comment]
- [ ] On the same page, choose a few postcodes, plus one or more categories for each, and display the 3 most up to date services.

For the above to be possible I will need to add services locations which currently isn't possible due to geocoding error.

**Comment by digitalWestie** [comment]
Ok, we can review at next meet

---
R. Gianni
Technology Consulting  •  Open Data Training  •  Software Development 
http://rgianni.cc <http://rgianni.cc>



24 Aug 2018, 17:03 by notifications@github.com:

**Comment by Mike-Heneghan** [comment]
Quirk of Python 3.6.5 with MacOSX. No certificates and cannot validate SSL connections. Necessary to run: ```/Applications/Python\ 3.6/Install\ Certificates.command``` as per https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error

Issue now resolved!

**Comment by Mike-Heneghan** [comment]
Accidentally deleted some of the services when trying to implement the updated in x weeks conditional in the AccountMyDigestView. Despite manually deleting all of the services and organistations I added the search still shows these services but when clicked on they can't be found. Must remain somewhere.

**Comment by Mike-Heneghan** [comment]
- [ ] Clear elasticsearch of the otherwise deleted test services

- [ ] Create a new view which returns 3 services updated for a given postcode and category

**Comment by Mike-Heneghan** [comment]
- [ ] Refactor ```AccountMyDigestView``` to have more than one postcode and category selection option (nested keys).

**Comment by Mike-Heneghan** [comment]
Create a new model digest_area, which stores user it belongs to, postcode, and many to many categories relationship (test by adding data to db via shell)

- [ ] Allow the user to just set the postcode with an optional category.
- [ ] ```digest_area``` will have a user, postcode and category.

**Comment by Mike-Heneghan** [comment]
- [ ] Create Form View for the user selected Postcode and Category

**Comment by Mike-Heneghan** [comment]
- [ ] Validate data such as postcode and category.
- [ ] Create the option to delete digests. 
- [ ] Pull in the category dropdown to the digest creation form.
