### ISSUE TITLE
Slightly clunky URL structure

### ISSUE THREAD

**Issue by djohnstonCC** [aliss/ALISS#3]
Environment:
Windows 10
Firefox 61.0.2 (64-bit)
Chrome Version 68.0.3440.106 (Official Build) (64-bit)

Steps to reproduce:

1. Visit homepage
2. Input postcode
3. Hit search button
4. 'Help & support in [POSTCODE]' page is displayed
5. Remove querystring text in address bar and hit enter - new address is: https://www.aliss.org/search or https://www.aliss.org/search/

Expected result:
Display some kind of functional search page

Actual result:
'Sorry, doesn't appear to be a valid postcode.' error page is displayed.

**Comment by digitalWestie** [comment]
Postcode is a requirement of search. Until this changes wontfix.
