### ISSUE TITLE
Inconsistent clickable areas in search result drop-downs

### ISSUE THREAD

**Issue by djohnstonCC** [aliss/ALISS#4]
Environment:
Windows 10
Firefox 61.0.2 (64-bit)
Chrome Version 68.0.3440.106 (Official Build) (64-bit)

Steps to reproduce:
Visit https://www.aliss.org/search/?postcode=g2+4aa&category=food-nutrition# 
Select elements are displayed indicating choices for 'Food & Nutrition' and 'Select Sub-Category'
Click anywhere in 'Food & Nutrition' select element, including on text label or white space

Expected behaviour:
Select element produces drop-down indicating further category choices.

Actual behaviour:
Select element does not produce drop-down choices unless down arrow at right is clicked. Clicking in white space or on 'Food & Nutrition' does not display drop-down options.

**Comment by digitalWestie** [comment]
fixed on master
