### ISSUE TITLE
'What is ALISS?' section - clickable category links

### ISSUE THREAD

**Issue by djohnstonCC** [aliss/ALISS#9]
The home page shows a 'What is ALISS?' section (`div class=row content for-not-for`) which includes two containers, one filled with things that ALISS does provide and the other things it doesn't. As these are the only category keywords featured on the home page it may be useful to render the provided services as links to the relevant search pages, using the geolocation API to provide a ballpark user location in place of a user-provided postcode. To indicate the existence of more keywords a link to a dedicated search page labelled as 'Explore other services' could be included at the end of the provided services list.

**Comment by digitalWestie** [comment]
Although most of these match up as service categories, the items just serve as text content, and are likely to be subject to change in near future so it won't be worth turning them into links atm.
